//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcupunturaWebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AcupunturaModelContainer : DbContext
    {
        public AcupunturaModelContainer()
            : base("name=AcupunturaModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Utilizador> UtilizadorSet { get; set; }
        public DbSet<Terapeuta> TerapeutaSet { get; set; }
        public DbSet<Paciente> PacienteSet { get; set; }
        public DbSet<Sintoma> SintomaSet { get; set; }
        public DbSet<Consulta> ConsultaSet { get; set; }
    }
}
